# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'production'
  appName: 'MyAngularApp1'    # Change to your Azure Web App name
  azureSubscription: 'Service_Connection_Automatic'
  appType: 'webApp'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration ${{ variables.buildConfiguration }} --base-href "./"
  displayName: 'Install dependencies and build Angular app'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/angular-standalone-app-with-routing/browser'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/angular.zip'
    
    replaceExistingArchive: true
  displayName: 'Archive Angular build'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/angular.zip'
    ArtifactName: 'artifact'
    publishLocation: 'Container'
  displayName: 'Publish artifact'
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(appName)'
    appType: '$(appType)'
    package: '$(Build.ArtifactStagingDirectory)/angular.zip'
  displayName: 'Deploy to Azure Web App'  

